name: PactSDK-Checks
on: [push]
jobs:
  Lint-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v7
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "1.29.2"
      - run: poetry install
      - name: Linting
        run: ./lint.sh
      - name: Building
        run: poetry build
      - name: Fetch contracts
        uses: actions/checkout@v2
        with:
          repository: "pactfi/algorand-testbed"
          path: algorand-testbed
      - run: cd algorand-testbed && poetry install
      - run: cd algorand-testbed && docker-compose up -d
      - run: poetry run pytest
